name: GitHub actions demo
run-name: Testing our Github actions

on: [push]

env:

  variable_example1: "This is the name"
  

jobs:
  basic_workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job basic_workflow is executing as part of new workflow"+$variable_example1
